[package]
name = "blobs"
version = "0.1.0"
authors = ["Magnus Sand√©n"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
